---
- name: Install dependencies required to setup a new version of docker
  sudo: yes
  apt: pkg={{ item }} state=latest
  tags: [packages]
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-apt

- name: Add new GPA Key
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  sudo: yes

- name: Add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
  
- name: Install Docker Engine
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
      - docker-engine
      
- name: Installing docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present