---
- name: installing Ruby as root
  command: "{{rvm_root}}/bin/rvm install {{rvm_default_ruby_version}}"
  sudo: true
  when: "'{{ rvm_install_type }}' == 'system'"

- name: installing Ruby as user
  command: "{{rvm_root}}/bin/rvm install {{rvm_default_ruby_version}}"
  sudo: yes
  when: "'{{ rvm_install_type }}' == 'user'"

- include: ./select_ruby.yml

- name: installing capistrano as user
  command: "gem install capistrano"
  when: "'{{ rvm_install_type }}' == 'user'"